name: pssswd
description: A cross-platform Password Management Application.

publish_to: 'none' 

version: 1.2.4+6

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  provider: ^6.0.3
  async: ^2.8.2
  encrypt: ^5.0.1
  crypt: ^4.2.1
  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.15
  fluttertoast: ^8.0.9
  firebase_auth: ^3.3.19
  firebase_auth_web: ^3.3.16
  flutter_secure_storage: ^5.0.2
  crypto: ^3.0.2
  hexcolor: ^2.0.7
  vibration: ^1.7.4-nullsafety
  slider_button: ^2.0.0
  pinput: ^2.2.10
  flutter_spinkit: ^5.1.0
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  random_string: ^2.3.1
  font_awesome_flutter: ^10.1.0
  url_strategy: ^0.2.0
  desktop_window: ^0.4.0
  url_launcher: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_config: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/pssswd-logo.png"
  image_path_android: "assets/images/pssswd-logo.png"
  adaptive_icon_background: "assets/images/pssswd_adaptive_back.png"
  adaptive_icon_foreground: "assets/images/pssswd_adaptive_fore.png"


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pssswd-logo.png
    - assets/images/pssswd-grey-scale-logo.png
    - assets/images/pssswd-gs-clipped.png

